# Generated by Django 5.2.15 on 2026-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homestays", "0002_homestay_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homestay",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="homestay",
            name="bedrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="homestay",
            name="breakfast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homestay",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homestay",
            name="max_guests",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="homestay",
            name="parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homestay",
            name="wifi",
            field=models.BooleanField(default=True),
        ),
    ]
