# Generated by Django 5.2.15 on 2026-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homestays", "0006_homestay_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
